sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=php:S2003
sonar.issue.ignore.multicriteria.e1.ruleKey=php:S4833
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.php
