services:
  web:
    build: .
    container_name: lund-web-app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./archive:/var/www/html/archive
      - ./img:/var/www/html/img
    env_file: .env # Passa DB_HOST, DB_NAME, ecc. a PHP
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.4.7
    container_name: lund-db-local
    restart: always
    command: 
      - --max_allowed_packet=512M
      - --innodb_buffer_pool_size=1G
      - --log-error=/var/log/mysql/error.log  # File normale invece di fd
      - --general-log=1
      - --general-log-file=/var/log/mysql/general.log  # File normale invece di fd
    env_file: .env
    environment:
      # Mappatura: Trasforma i nomi agnostici in nomi tecnici MySQL
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - lund_db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "--password=${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  lund_db_data: