site_name: Dynamic Collections Plus
site_url: https://dyncolldev.ht.lu.se/plus/
repo_url: https://github.com/LundDarkLab/adc
theme:
  name: readthedocs
nav:
  - Home: index.md
  - About: about.md
  - Requirements: requirements.md
  - Installation: installation.md